# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc53ad19906e56270a6725b3817b1892d49758b4fd372043eec24bdc909383ab2255ed6b5ac68aad4df189952fb5297269678f861da55b5fd932d6e19428dd1

test:
  secret_key_base: 5b236a1a9ecc54ce11fcbe27b6b7b5541d77ef92aec2378ea6a5f16d572ce3907732079564078ee515492f1e3fdc2247225ce4384937fc5a9754f0467feddfe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
